ARG BASE_VERSION=latest
FROM nexusprod.corp.intranet:4567/jsl-docker-standard-images/node14_agent:$BASE_VERSION

ARG user=jenkins
ARG group=jenkins

WORKDIR /home/${user}
ENV CURLOPTIONS "-SsLk --fail"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# https://www.slimjet.com/chrome/download-chrome.php?file=files%2F86.0.4240.75%2Fgoogle-chrome-stable_current_amd64.deb
# https://www.slimjet.com/chrome/download-chrome.php?file=files%2F71.0.3578.80%2Fgoogle-chrome-stable_current_amd64.deb

RUN apt-get update && \
    apt-get remove -y google-chrome-stable && \
    curl ${CURLOPTIONS} https://www.slimjet.com/chrome/download-chrome.php?file=files%2F71.0.3578.80%2Fgoogle-chrome-stable_current_amd64.deb -o google-chrome-stable_current_amd64.deb && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get --no-install-recommends -yqq install ./google-chrome-stable_current_amd64.deb expect libgconf-2-4 xvfb busybox && \
    rm ./google-chrome-stable_current_amd64.deb && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget "https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz" -O hub.tgz \
    && tar xzvf hub.tgz \
    && mv hub-linux-amd64-2.14.2/bin/hub /usr/local/bin \
    && chmod +x /usr/local/bin/hub

ENV QT_X11_NO_MITSHM=1
ENV _X11_NO_MITSHM=1
ENV _MITSHM=0
ENV TERM=xterm-256color

RUN ls -la /root
RUN chmod 755 /root

USER ${user}