export const COMMON_SIZES = ['xs', 'sm', 'md', 'lg'];
export const ICON_SIZES = ['xs', 'sm--2', 'sm--3', ...COMMON_SIZES, 'xl', 'xxl'];
export const MARKETING_ICON_SIZES = ['xs', ...COMMON_SIZES];
export const TEXT_INPUT_SIZES = ['xs', ...COMMON_SIZES, 'xl'];
export const LABEL_SIZES = ['xs', ...COMMON_SIZES, 'xl'];
export const TABS_SIZES = ['xs', ...COMMON_SIZES, 'xl'];
export const ACCORDION_SIZES = [...COMMON_SIZES, 'xl'];
export const PICKER_SIZES = ['md', 'lg'];
export const PICKER_PILL_SIZES = ['xs', 'sm'];
