files:
  include: '**/*.scss'
  exclude: 'src/boilerplates/**/*'
options:
  formatter: stylish
rules:
  attribute-quotes: 2
  bem-depth: 2
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: true
  class-name-format:
    - 0
    - convention: '^(chi|([amo]-[a-z][a-zA-Z0-9]*(__[a-z][a-zA-Z0-9]*)*)|(-[a-z][-a-zA-Z0-9]*))$'
    - convention-explanation: 'class must be a valid A-B__E (A=[a|m|o] atomicIdentifier, B=blockName, E=elementName) or -M (M=modifierName) identifier'
  clean-import-paths:
    - 1
    - leading-underscore: true
    - filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks:
    - 2
    - include: true
    - allow-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  hex-length:
    - 2
    - style: 'long'
  hex-notation:
    - 2
    - style: 'lowercase'
  id-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count: 0
  max-line-length:
    - 2
    - length: 120
  mixin-name-format:
    - 2
    - allow-leading-underscore: fales
    - convention: 'hyphenatedlowercase'
  mixins-before-declarations: 0
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 2
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties:
    - 2
    - properties: []
  no-duplicate-properties:
    - 1
    -
      exclude:
        - color
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    - allow-element-with-class: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2

  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  property-sort-order: 0
  property-units:
    - 2
    - global:
      - rem
      - px
      - s
  pseudo-element: 2
  quotes:
    - 2
    - style: 'single'
  shorthand-values:
    - 2
    -
      allowed-shorthands:
        - 1
        - 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  zero-unit:
    - 2
    - include: false
