<template lang="pug">
<TitleAnchor title="Name, role, value" id="name-role-value" titleSize="h2" />
.chi-grid
  .chi-col.-w--12
    .chi-breadcrumb
      ol.-text--normal
        li.chi-breadcrumb__item(v-for="({ url, text }) in breadcrumbs")
          a(:href="url" rel="noopener" target="_blank") {{ text }}
  .chi-col.-w--12
    .-lh--3
      .chi-badge.-dark.-outline.-xs.-mr--1(v-for="({ tooltipText, mainText }) in badges" :data-tooltip="tooltipText" data-position="bottom")
        span {{ mainText }}
  .chi-col.-w--12
    p.-text
      | <strong>Benefits:</strong> All disabilities using Assistive Technologies.
    p.-text
      | For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user
      | can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.
    p.-text
      | <strong>Note:</strong> This success criterion is primarily for Web authors who develop or script their own user interface components. For example, standard HTML controls already meet this success criterion when used according to specification.
  .chi-col.-w--12
    .chi-card.-s--1.-rounded.-mb--3.-mt--1
      .chi-card__header
        .chi-card__title How to pass
      .chi-card__content.-px--3
        ul.accessibility-checklist
          li(v-for="item in checklist") {{ item }}
</template>

<script lang="ts">
import { Vue } from 'vue-facing-decorator';

@NuxtComponent({
  data: () => {
    return {
      breadcrumbs: [
        {
          url: 'https://www.w3.org/TR/WCAG20',
          text: 'WCAG 2.0 Guideline',
        },
        {
          url: 'https://www.w3.org/TR/WCAG20/#ensure-compat',
          text: '4.1 Compatible',
        },
        {
          url: 'https://www.w3.org/TR/WCAG20/#ensure-compat-rsv',
          text: '4.1.2 Name, Role, Value',
        },
      ],
      badges: [
        {
          tooltipText: 'Users must be able to access the content as technologies advance.',
          mainText: 'Robust',
        },
        {
          tooltipText: 'Requirements must be satisfied to pass WCAG 2.0 Level A Success Criteria.',
          mainText: 'Level A',
        },
      ],
      checklist: [
        'If custom controls are created, or interface elements are programmed (in code or script) that have a different role and/or function than usual, are additional measures used to ensure that the controls provide important information to Assistive Technologies and can be controlled by assistive technologies.',
      ],
    };
  },
})
export default class NameRoleValue extends Vue {}
</script>
