import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export const ROOT = process.env.CHI_ROOT || join(__dirname, '../..');
export const CHI_SRC = process.env.CHI_SRC || join(ROOT, 'src/chi');
export const SKILLS_DIR = join(ROOT, '.cursor/skills');
export const RULES_DIR = join(ROOT, '.cursor/rules');
export const OUTPUT_PATH = join(ROOT, 'src/mcp/metadata.json');
export const BUILD_CACHE_PATH = join(__dirname, '.build-cache.json');

export const THEMES = ['lumen', 'brightspeed', 'centurylink', 'colt', 'portal', 'connect'] as const;
export type Theme = (typeof THEMES)[number];

export const KNOWN_WC_TAGS = new Set([
  'chi-accordion',
  'chi-alert',
  'chi-backdrop',
  'chi-badge',
  'chi-brand',
  'chi-breadcrumb',
  'chi-button',
  'chi-cache-loader',
  'chi-card',
  'chi-carousel',
  'chi-checkbox',
  'chi-copy-text',
  'chi-customize-panel',
  'chi-date',
  'chi-date-picker',
  'chi-drag',
  'chi-drawer',
  'chi-dropdown',
  'chi-dropdown-select',
  'chi-expansion-panel',
  'chi-form-wrapper',
  'chi-helper-message',
  'chi-icon',
  'chi-info-icon',
  'chi-label',
  'chi-link',
  'chi-main',
  'chi-marketing-icon',
  'chi-modal',
  'chi-number-input',
  'chi-pagination',
  'chi-phone-input',
  'chi-picker',
  'chi-picker-group',
  'chi-popover',
  'chi-price',
  'chi-progress',
  'chi-radio-button',
  'chi-search-input',
  'chi-skeleton',
  'chi-spinner',
  'chi-switch',
  'chi-tabs',
  'chi-tags',
  'chi-text-input',
  'chi-textarea',
  'chi-time',
  'chi-time-picker',
  'chi-toolbar',
  'chi-tooltip',
]);

/** Maps CSS base classes that differ from their Web Component tag name. */
export const CSS_TO_WC_OVERRIDES: Record<string, string> = {
  'chi-datepicker': 'chi-date-picker',
  'chi-epanel': 'chi-expansion-panel',
  'chi-input': 'chi-text-input',
  'chi-search': 'chi-search-input',
  'chi-radio': 'chi-radio-button',
};

export const COMP_CATEGORIES: Record<string, string[]> = {
  Actions: ['buttons', 'link'],
  Forms: [
    'checkbox',
    'radio',
    'input-text',
    'input-file',
    'textarea',
    'label',
    'form-wrapper',
    'phone-input',
    'number-input',
    'html-select',
    'search-input',
    'toggle-switch',
  ],
  'Data Display': [
    'data-table',
    'tables',
    'badge',
    'card',
    'avatars',
    'brand',
    'price',
    'progress',
    'skeleton',
    'copy-text',
    'stat',
    'transfer-list',
  ],
  Feedback: ['alert', 'spinner', 'tooltip', 'drawer', 'cache-loader'],
  Navigation: [
    'breadcrumb',
    'navigation',
    'pagination',
    'header',
    'footer',
    'sidebar',
    'toolbar',
    'mobile-navigation',
    'steps',
  ],
  Overlays: ['modal', 'popover', 'dropdown', 'backdrop'],
  Layout: [
    'grid',
    'css-grid',
    'divider',
    'app-layout',
    'main',
    'expansion-panel',
    'accordion',
    'carousel',
    'customize-panel',
    'bulk-actions',
    'filters',
    'save-view',
    'save-views',
  ],
  Media: ['icons', 'marketing-icon', 'flag-icon'],
  Pickers: ['date-picker', 'time-picker', 'picker', 'picker-group'],
};

export const COMP_DESCRIPTIONS: Record<string, string> = {
  accordion: 'Expandable/collapsible content panels for organizing information in vertical stacks',
  activity: 'Activity feed displaying chronological events or user actions',
  main: 'Primary content area wrapper for the application layout',
  alert: 'Contextual feedback messages with severity levels (success, warning, danger, info)',
  'app-layout': 'Top-level application layout container for header, sidebar, and content areas',
  avatars: 'Circular user profile image or initials placeholder with size variants',
  backdrop: 'Semi-transparent overlay background used behind modals and drawers',
  badge: 'Small status indicator or count label, often attached to icons or buttons',
  brand: 'Brand logo component for Lumen, CenturyLink, Brightspeed, and Colt themes',
  breadcrumb: 'Navigation trail showing the current page location within a hierarchy',
  'bulk-actions': 'Toolbar for batch operations on selected items in a list or table',
  buttons: 'Interactive element for triggering actions, with color, size, and variant options',
  'cache-loader': 'Loading indicator with pulse or bar animation for cached content',
  card: 'Flexible content container with header, body, footer, and interactive states',
  carousel: 'Horizontally scrollable content viewer with navigation controls',
  checkbox: 'Form control for binary or indeterminate selection with label support',
  'copy-text': 'Text display with one-click copy-to-clipboard functionality',
  'css-grid': 'CSS Grid layout utility for responsive multi-column/row layouts',
  'customize-panel': 'Panel for user customization of table columns or display preferences',
  'data-table': 'Feature-rich table with sorting, selection, expansion, and striped rows',
  'date-picker': 'Calendar-based date selection input with month/year navigation',
  divider: 'Visual separator line between content sections, horizontal or vertical',
  'drag-and-drop': 'Draggable item container for reordering lists or panels',
  drawer: 'Slide-in panel from any edge of the screen for secondary content',
  dropdown: 'Toggle-activated menu or select list with keyboard navigation',
  'expansion-panel': 'Stepped workflow panel with expand/collapse, numbering, and state indicators',
  filters: 'Filter controls container for narrowing data table or list results',
  'flag-icon': 'Country flag icon for internationalization and locale selection',
  footer: 'Page footer with links, icons, and layout options',
  'form-wrapper': 'Form field wrapper providing consistent label, input, and helper message layout',
  grid: 'Responsive 12-column flexbox grid system with gutters and alignment',
  header: 'Page header with navigation bar, branding, and responsive collapse',
  'html-select': 'Styled native HTML select dropdown element',
  icons: 'SVG icon component from the Chi icon library with size variants',
  'input-file': 'File upload input with drag-and-drop support',
  'input-number': 'Numeric input with increment/decrement buttons and range validation',
  'number-input': 'Numeric input with increment/decrement buttons and range validation',
  'input-text': 'Text input field with label, helper message, and validation states',
  label: 'Form field label with required/optional indicator and status colors',
  link: 'Styled anchor element with hover, CTA, and disabled states',
  'marketing-icon': 'Illustrative marketing icon for feature highlights and promotions',
  'mobile-navigation': 'Responsive mobile navigation menu with slide-in panels',
  modal: 'Dialog overlay that traps focus and requires user interaction before returning to the page',
  navigation: 'Tab-based navigation with horizontal/vertical orientation and sliding borders',
  pagination: 'Page navigation controls with numbered pages, prev/next, and compact mode',
  'phone-input': 'International phone number input with country code selector',
  picker: 'Single-select option picker with pill or standard style',
  'picker-group': 'Multi-option picker group with fluid layout and alignment options',
  popover: 'Floating content panel anchored to a trigger element, with close and drag support',
  price: 'Formatted price display with superscript decimals and size variants',
  progress: 'Progress bar or indicator showing completion percentage',
  radio: 'Form control for single selection from a group of options',
  'save-view': 'Control for saving and managing custom table or list view configurations',
  'save-views': 'Container for multiple saved view configurations',
  'search-input': 'Text input with search icon and clear button for filtering content',
  sidebar: 'Collapsible side navigation panel with multi-level menu support',
  skeleton: 'Placeholder loading animation mimicking content shape before data loads',
  spinner: 'Animated loading indicator with size and color variants',
  stat: 'Statistical metric display with icon, value, and label',
  steps: 'Step indicator for multi-step workflows with active/completed states',
  tables: 'Data table with sorting, row states (success/warning/danger), and striped rows',
  tags: 'Removable label or keyword tag with close button and icon support',
  textarea: 'Multi-line text input with auto-resize support',
  'time-picker': 'Time selection input with hour/minute controls',
  'toggle-switch': 'Binary toggle switch with label and size variants',
  toolbar: 'Horizontal or vertical toolbar for grouping action buttons and controls',
  tooltip: 'Small popup hint that appears on hover or focus, with light/dark themes',
  'transfer-list': 'Dual-list component for moving items between available and selected lists',
};

export const SIZE_MODS = new Set(['-xs', '-sm', '-sm--2', '-sm--3', '-md', '-lg', '-xl', '-xxl']);
export const COLOR_MODS = new Set([
  '-primary',
  '-secondary',
  '-dark',
  '-light',
  '-danger',
  '-success',
  '-warning',
  '-info',
  '-muted',
  '-inverse',
]);
export const STATE_MODS = new Set(['-active', '-disabled', '-checked', '-closable', '-expanded']);
export const POSITION_MODS = new Set(['-top', '-right', '-bottom', '-left']);
export const VARIANT_MODS = new Set(['-flat', '-outline']);
export const BOOLEAN_MODS = new Set([
  '-pill',
  '-fluid',
  '-vertical',
  '-horizontal',
  '-border',
  '-sliding-border',
  '-animate',
  '-hover',
  '-bordered',
  '-compact',
  '-portal',
  '-required',
  '-optional',
  '-cta',
  '-no-underline',
]);
