export declare const COMMON_SIZES: readonly ["xs", "sm", "md", "lg"];
export declare const ICON_SIZES: string[];
export declare const MARKETING_ICON_SIZES: ("xs" | "sm" | "md" | "lg")[];
export declare const TEXT_INPUT_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const LABEL_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const TABS_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const SKELETON_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const ACCORDION_SIZES: readonly ["sm", "md", "lg", "xl"];
export declare const PICKER_SIZES: string[];
export declare const PICKER_PILL_SIZES: string[];
export declare const PRICE_SIZES: string[];
export type TextInputSizes = (typeof TEXT_INPUT_SIZES)[number];
export type IconSizes = (typeof ICON_SIZES)[number];
export type MarketingIconSizes = (typeof MARKETING_ICON_SIZES)[number];
export type TabsSizes = (typeof TABS_SIZES)[number];
export type SkeletonSizes = (typeof SKELETON_SIZES)[number];
export type LabelSizes = (typeof LABEL_SIZES)[number];
export type AccordionSizes = (typeof ACCORDION_SIZES)[number];
export type PickerSizes = (typeof PICKER_SIZES)[number];
export type PickerPillSizes = (typeof PICKER_PILL_SIZES)[number];
export type PriceSizes = (typeof PRICE_SIZES)[number];
