export declare const ICON_SIZES: string[];
export declare const MARKETING_ICON_SIZES: string[];
export declare const TEXT_INPUT_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const LABEL_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export declare const TABS_SIZES: readonly ["xs", "sm", "md", "lg", "xl"];
export type TextInputSizes = (typeof TEXT_INPUT_SIZES)[number];
export type IconSizes = (typeof ICON_SIZES)[number];
export type MarketingIconSizes = (typeof MARKETING_ICON_SIZES)[number];
export type TabsSizes = (typeof TABS_SIZES)[number];
export type LabelSizes = (typeof LABEL_SIZES)[number];
